---
include:
  - project: slxh/pipelines
    file:
      - latex.gitlab-ci.yml

variables:
  PACKAGE: raleway

build:
  stage: build
  script:
    - tlmgr remove raleway --force
    - make fonts
    - cp -a $CI_PROJECT_DIR/* /usr/local/texlive/texmf-local
    - echo Map Raleway.map > /usr/local/texlive/texmf-local/web2c/updmap.cfg
    - find /usr/local/texlive/texmf-local
    - texhash
    - updmap-sys
    - make
  artifacts:
    paths:
      - "*.pdf"
      - "*.zip"
