---
include:
  - project: slxh/pipelines
    file:
      - latex.gitlab-ci.yml

variables:
  PACKAGE: sourcesans

build:
  stage: build
  script:
    - make fonts
    - cp -a $CI_PROJECT_DIR/* /usr/local/texlive/texmf-local
    - echo Map SourceSansThree.map > /usr/local/texlive/texmf-local/web2c/updmap.cfg
    - texhash
    - updmap-sys
    - make
  artifacts:
    paths:
      - "*.zip"
